services:
  test-runner:
    image: maven:3.9.9-eclipse-temurin-21
    container_name: booklovers-test
    working_dir: /app
    volumes:
      - ./booklovers:/app
    command: mvn clean verify -Dspring.profiles.active=test
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - MAVEN_OPTS=-Xmx2048m -XX:MaxMetaspaceSize=512m
    mem_limit: 3g